spring:
  application:
    name: pos-system

  datasource:
    url: jdbc:mysql://mysql-23c21abf-achininirupama98-af18.d.aivencloud.com:19141/pos_sys
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: avnadmin
    password: AVNS_Qos-3KNcEN0dRPcMQVh
    # Ensure JDBC driver uses UTC
    properties:
      serverTimezone: UTC

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        # Store timestamps in UTC
        jdbc.time_zone: UTC

    show-sql: true
    # JSON serialization timezone
    jackson:
      time-zone: Asia/Colombo
      date-format: yyyy-MM-dd'T'HH:mm:ss

  mail:
    host: smtp.gmail.com
    port: 587
    username: nalindadsn@gmail.com
    password: 941151663Bandara
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  devtools:
    livereload:
      enabled: true

server:
  port: 5000

razorpay:
  api:
    key: your razor pay key
    secret: your razorpay secret key

stripe:
  api:
    key: your stripe key

app:
  frontend:
    reset-url: https://pos-frontend-eight-lyart.vercel.app/auth/reset-password?token=

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
